language: shell

dist: xenial

before_install:
  - pip install --user cpp-coveralls codecov
  - sudo apt-get update
  - sudo apt-get -y install lcov bzip2 wget cmake make gcc libboost-system-dev libboost-filesystem-dev libboost-timer-dev libboost-thread-dev libboost-program-options-dev
  - sudo bash resources/install_dynadjust_prerequisites.sh -m 1

install:
   - cd ..
   - cp ./DynAdjust/resources/make_dynadjust_gcc.sh ./
   - sudo bash make_dynadjust_gcc.sh --no-install --auto --do-not-clone --test
   - cd ./DynAdjust

#script:
#  - cd ./sampleData && bash run-gnss-network.sh
  
after_success:
#  - coveralls --root . -E ".*CMakeFiles.*" 
#   - coveralls --root . --verbose --exclude-pattern ".*feature_tests.*" --exclude-pattern ".*CompilerId.*" --gcov-options '\-lp'
   - coveralls -- root ./dynadjust/build_gcc --gcov-options '\-lp'
   - bash <(curl -s https://codecov.io/bash)
