language: cpp

compiler:
  - gcc

dist: xenial

cache:
  apt: true

branches:
  only:
    - master

before_install:
  - pip install --user cpp-coveralls codecov
  - sudo apt-get update
  - sudo apt-get -y install lcov bzip2 wget cmake make gcc libboost-system-dev libboost-filesystem-dev libboost-timer-dev libboost-thread-dev libboost-program-options-dev
  - sudo bash resources/install_dynadjust_prerequisites.sh -m 1

script:
   - cd ..
   - cp ./DynAdjust/resources/make_dynadjust_gcc.sh ./
   - sudo bash make_dynadjust_gcc.sh --no-install --auto --do-not-clone --test
  
after_success:
   - cd ./DynAdjust/dynadjust/build_gcc
#  - coveralls --root . -E ".*CMakeFiles.*" 
#  - coveralls --root . --verbose --exclude-pattern ".*feature_tests.*" --exclude-pattern ".*CompilerId.*" --gcov-options '\-lp'
   - coveralls 
     --root ../../
     --build-root ./
     --gcov-options '\--long-file-names --preserve-paths' 
     --verbose
     --gcov /usr/bin/gcov
     --exclude-pattern ".*CMakeFiles.*" 
     --exclude-pattern ".*CompilerId.*"
   - bash <(curl -s https://codecov.io/bash)
