language: shell

dist: xenial

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get update
  - sudo apt-get -y install bzip2 wget cmake make gcc libboost-system-dev libboost-filesystem-dev libboost-timer-dev libboost-thread-dev libboost-program-options-dev
  - sudo bash resources/install_dynadjust_prerequisites.sh -m 1

install:
   - cd ..
   - cp ./DynAdjust/resources/make_dynadjust_gcc.sh ./
   - sudo bash make_dynadjust_gcc.sh -c 1
   - cd ./DynAdjust

#script:
#  - cd ./sampleData && bash run-gnss-network.sh
  
after_success:
#  - coveralls --root . -E ".*CMakeFiles.*" 
   - coveralls --gcov-options '\-lp'
   - bash <(curl -s https://codecov.io/bash)
