language: shell

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get -y install bzip2 wget cmake make gcc libboost-all-dev
  - sudo bash resources/install_dynadjust_prerequisites.sh -m 1

install:
   - cd ..
   - cp ./DynAdjust/resources/make_dynadjust_gcc.sh ./
   - sudo bash make_dynadjust_gcc.sh -c 1

#script:
#  - cd ../sampleData && bash run-gnss-network.sh
